# NOTE: If you are trying to run this off of your fork, you have to change the
# docroot in travis/configuration.inc.php from /qcubed/ to the name of your fork.
language: php

php:
    - 5.4

install:
    - composer install

env:
    - DB=mysql
    - DB=pgsql

before_script:
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database qcubed;'; mysql -u root qcubed < assets/php/examples/mysql_innodb.sql; fi"
    - sh -c "if [ '$DB' = 'pgsql' ]; then createdb qcubed -U postgres; psql -d qcubed -f assets/php/examples/pgsql.sql -U postgres; fi"

script: travis/test.php

